#!/bin/bash

FILES_REQUIRED=(0-select_states.py 1-filter_states.py 2-my_filter_states.py 3-my_safe_filter_states.py 4-cities_by_state.py 5-filter_cities.py )

for i in "${FILES_REQUIRED[@]}";do
touch $i;
echo "#!/usr/bin/python3" >> $i
done